import {resolve} from "path";

export default {
    "index": resolve(__dirname, "src/index.ts"),
    "composables/index": resolve(__dirname, "src/composables/index.ts"),
    "directives/index": resolve(__dirname, "src/directives/index.ts"),
    "shared/index": resolve(__dirname, "src/shared/index.ts"),
    "components/index": resolve(__dirname, "src/components/index.ts"),
    "components/Accordion/index": resolve(__dirname, "src/components/Accordion/index.ts"),
    "components/Alert/index": resolve(__dirname, "src/components/Alert/index.ts"),
    "components/Breadcrumb/index": resolve(__dirname, "src/components/Breadcrumb/index.ts"),
    "components/Button/index": resolve(__dirname, "src/components/Button/index.ts"),
    "components/Card/index": resolve(__dirname, "src/components/Card/index.ts"),
    "components/Carousel/index": resolve(__dirname, "src/components/Carousel/index.ts"),
    "components/Dropdown/index": resolve(__dirname, "src/components/Dropdown/index.ts"),
    "components/Form/index": resolve(__dirname, "src/components/Form/index.ts"),
    "components/Indicators/index": resolve(__dirname, "src/components/Indicators/index.ts"),
    "components/Layout/index": resolve(__dirname, "src/components/Layout/index.ts"),
    "components/ListGroup/index": resolve(__dirname, "src/components/ListGroup/index.ts"),
    "components/Modal/index": resolve(__dirname, "src/components/Modal/index.ts"),
    "components/Native/index": resolve(__dirname, "src/components/Native/index.ts"),
    "components/Navigation/index": resolve(__dirname, "src/components/Navigation/index.ts"),
    "components/Notification/index": resolve(__dirname, "src/components/Notification/index.ts"),
    "components/Offcanvas/index": resolve(__dirname, "src/components/Offcanvas/index.ts"),
    "components/Tab/index": resolve(__dirname, "src/components/Tab/index.ts"),
    "components/Table/index": resolve(__dirname, "src/components/Table/index.ts"),
    "components/Ui/index": resolve(__dirname, "src/components/Ui/index.ts"),
}